kanban_homepage:
    path:     /
    defaults: { _controller: KanbanBundle:Default:index }

list:
    path:     /list
    defaults: { _controller: KanbanBundle:Tache:list }

edit:
    path:     /edit/{idTache}
    defaults: { _controller: KanbanBundle:Tache:edit }

create:
    path:     /create
    defaults: { _controller: KanbanBundle:Tache:create }

delete:
    path:     /delete/{idTache}
    defaults: { _controller: KanbanBundle:Tache:delete }

etat:
    path:    /etat/{idTache}/{etat}
    defaults: { _controller: KanbanBundle:Tache:etat }


